"""add_fields_to_taller

Revision ID: 208a8cb587d1
Revises: 344145ea3d79
Create Date: 2026-04-03 07:46:06.966230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208a8cb587d1'
down_revision: Union[str, Sequence[str], None] = '344145ea3d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_talleres', sa.Column('nit', sa.String(length=50), nullable=True))
    op.add_column('perfil_talleres', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('perfil_talleres', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('perfil_talleres', sa.Column('foto_perfil', sa.String(length=255), nullable=True))
    op.add_column('perfil_talleres', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('perfil_talleres', sa.Column('longitud', sa.Float(), nullable=True))
    op.alter_column('perfil_talleres', 'nombre_comercial',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfil_talleres', 'nombre_comercial',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('perfil_talleres', 'longitud')
    op.drop_column('perfil_talleres', 'latitud')
    op.drop_column('perfil_talleres', 'foto_perfil')
    op.drop_column('perfil_talleres', 'direccion')
    op.drop_column('perfil_talleres', 'ciudad')
    op.drop_column('perfil_talleres', 'nit')
    # ### end Alembic commands ###
