"""genesis_completo

Revision ID: 403fe125fd86
Revises: 
Create Date: 2026-04-20 18:02:22.737056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403fe125fd86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN_TALLER', 'PERSONAL_TALLER', 'CLIENTE', name='userrole'), nullable=False),
    sa.Column('tipo_perfil', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('perfil_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('ci', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_taller', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['perfil_talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['perfil_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('emergencias',
    sa.Column('nro', sa.Integer(), nullable=False),
    sa.Column('ubicacion_real', sa.String(), nullable=True, comment='Coordenadas GPS del lugar del incidente'),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('prioridad', sa.Enum('alta', 'media', 'baja', name='prioridademergencia'), nullable=True),
    sa.Column('estado', sa.Enum('espera', 'atendiendo', 'cancelado', 'terminado', name='estadoemergencia'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_personal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personal'], ['personal_taller.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('nro')
    )
    op.create_index(op.f('ix_emergencias_nro'), 'emergencias', ['nro'], unique=False)
    op.create_table('detalle_emergencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_emergencia', sa.Integer(), nullable=True),
    sa.Column('tiempo_llegada_estimado', sa.String(length=50), nullable=True),
    sa.Column('ubicacion_personal_real', sa.String(), nullable=True, comment='Ubicación GPS actual del mecánico'),
    sa.ForeignKeyConstraint(['nro_emergencia'], ['emergencias.nro'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_emergencia')
    )
    op.create_index(op.f('ix_detalle_emergencias_id'), 'detalle_emergencias', ['id'], unique=False)
    op.create_table('mensajeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_emergencia', sa.Integer(), nullable=False),
    sa.Column('id_remitente', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=1000), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_remitente'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['nro_emergencia'], ['emergencias.nro'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajeria_id'), 'mensajeria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajeria_id'), table_name='mensajeria')
    op.drop_table('mensajeria')
    op.drop_index(op.f('ix_detalle_emergencias_id'), table_name='detalle_emergencias')
    op.drop_table('detalle_emergencias')
    op.drop_index(op.f('ix_emergencias_nro'), table_name='emergencias')
    op.drop_table('emergencias')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('personal_taller')
    op.drop_table('perfil_talleres')
    op.drop_table('perfil_clientes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
