"""fix multiple foreign keys in emergencia

Revision ID: 9884f11be9e6
Revises: a61d2327091a
Create Date: 2026-04-25 12:46:49.320157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9884f11be9e6'
down_revision: Union[str, Sequence[str], None] = 'a61d2327091a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
