"""agregar id_taller a emergencias

Revision ID: a61d2327091a
Revises: 403fe125fd86
Create Date: 2026-04-24 22:49:06.511860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61d2327091a'
down_revision: Union[str, Sequence[str], None] = '403fe125fd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones_talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Float(), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('fecha_calificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['perfil_clientes.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['perfil_talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calificaciones_talleres_id'), 'calificaciones_talleres', ['id'], unique=False)
    op.add_column('emergencias', sa.Column('id_taller', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emergencias', 'usuarios', ['id_taller'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emergencias', type_='foreignkey')
    op.drop_column('emergencias', 'id_taller')
    op.drop_index(op.f('ix_calificaciones_talleres_id'), table_name='calificaciones_talleres')
    op.drop_table('calificaciones_talleres')
    # ### end Alembic commands ###
