"""add ci and birthdate to cliente

Revision ID: d493fb3db82e
Revises: 8f1202f1054c
Create Date: 2026-04-15 17:48:05.248181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd493fb3db82e'
down_revision: Union[str, Sequence[str], None] = '8f1202f1054c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_clientes', sa.Column('ci', sa.String(length=20), nullable=True))
    op.add_column('perfil_clientes', sa.Column('fecha_nacimiento', sa.String(length=50), nullable=True))
    op.add_column('perfil_clientes', sa.Column('foto_perfil', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil_clientes', 'foto_perfil')
    op.drop_column('perfil_clientes', 'fecha_nacimiento')
    op.drop_column('perfil_clientes', 'ci')
    # ### end Alembic commands ###
