"""add diagnostico_ia

Revision ID: ddac15928e00
Revises: 68bf88586e58
Create Date: 2026-04-27 14:06:51.771527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddac15928e00'
down_revision: Union[str, Sequence[str], None] = '68bf88586e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    op.add_column('emergencias', sa.Column('diagnostico_ia', sa.String(length=2000), nullable=True, comment='Diagnóstico y evaluación generada por IA'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencias', 'diagnostico_ia')
    op.create_table('bitacora',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('agente', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('detalle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_taller', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_taller'], ['perfil_talleres.id'], name=op.f('bitacora_id_taller_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('bitacora_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bitacora_pkey'))
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    # ### end Alembic commands ###
